### ISSUE TITLE
Cmake warning for `Hpf-fcl` to `coal `

### ISSUE THREAD

**Issue by lukas-ramlab** [stack-of-tasks/pinocchio#2512] opened 2024-12-13 08:43 UTC
## Bug description
On cmake with pinocchio I get following two warnings:
```
CMake Warning at /opt/openrobots/lib/cmake/hpp-fcl/hpp-fclConfig.cmake:3 (message):
  Please update your CMake from 'hpp-fcl' to 'coal'
Call Stack (most recent call first):
  /usr/share/cmake-3.31/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)
  /opt/openrobots/lib/cmake/pinocchio/pinocchioConfig.cmake:161 (find_dependency)
  lib/kinematics/CMakeLists.txt:22 (find_package)


-- coal not FOUND.
```
And further below:
```
In file included from /opt/openrobots/include/hpp/fcl/config.hh:1,
                 from /opt/openrobots/include/pinocchio/serialization/eigen.hpp:20,
                 from /opt/openrobots/include/pinocchio/serialization/fwd.hpp:11,
                 from /opt/openrobots/include/pinocchio/multibody/joint/joint-composite.hpp:14,
                 from /opt/openrobots/include/pinocchio/multibody/joint/joint-generic.hpp:9,
                 from /opt/openrobots/include/pinocchio/multibody/model.hpp:17,
                 from /opt/openrobots/include/pinocchio/parsers/urdf.hpp:9,
                 from /opt/MaxQ/mc-backend/lib/kinematics/include/kinematics/urdf.hpp:10,
                 from /opt/MaxQ/mc-backend/lib/kinematics/src/urdf.cpp:1:
/opt/openrobots/include/hpp/fcl/coal.hpp:13:2: warning: #warning "Please update your includes from 'hpp/fcl' to 'coal'" [-Wcpp]
```

### System
cmake version 3.31.2
Ubuntu 22.04.5 LTS (docker container)
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by jorisv** [comment] 2024-12-13 08:48
Hello,
It's normal, for now, pinocchio use the hpp-fcl compatibility layer to coal. This layer add this warning to encourage to use the new API.
We will soon use coal instead of hpp-fcl and this will remove this warning.

Duplicate of https://github.com/stack-of-tasks/pinocchio/issues/2480

**Closed by jorisv** 2024-12-13 08:48 UTC
