### ISSUE TITLE
ImportError: No module named pinocchio

### ISSUE THREAD

**Issue by ShihaoWang** [stack-of-tasks/pinocchio#625] opened 2018-12-29 01:28 UTC
Hi,
I have already successfully installed pinocchio on my OS ubuntu **14.04** according to the instruction(**build from source**). However, when I run the python examples, I was told that pinocchio cannot be found:
```
shihao@shihao-OptiPlex-7040:~/pinocchio/examples/python$ python fd-derivatives.py 
Traceback (most recent call last):
  File "fd-derivatives.py", line 20, in <module>
    import pinocchio as pin
ImportError: No module named pinocchio
```
I think that it should be a path problem, so I add **/usr/local/lib/python2.7/site-packages/** to the python sys.path. However, this path addition brings about another error
```
shihao@shihao-OptiPlex-7040:~/pinocchio/examples/python$ python fd-derivatives.py 
Traceback (most recent call last):
  File "fd-derivatives.py", line 20, in <module>
    import pinocchio as pin
  File "/usr/local/lib/python2.7/site-packages/pinocchio/__init__.py", line 18, in <module>
    from pinocchio.robot_wrapper import RobotWrapper
  File "/usr/local/lib/python2.7/site-packages/pinocchio/robot_wrapper.py", line 17, in <module>
    from . import libpinocchio_pywrap as se3
ImportError: libpinocchio.so: cannot open shared object file: No such file or directory
```
I am not sure what I should do next. Can you help me with this problem?

**Comment by jcarpent** [comment] 2018-12-29 08:09
Hi @ShihaoWang,

It seems that you have correctly installed Pinocchio and its Python bindings.
In order to debug your configuration, can you display the content of **/usr/local/lib/python2.7/site-packages/pinocchio** with:
```
ls -l /usr/local/lib/python2.7/site-packages/pinocchio
```

**Comment by jmirabel** [comment] 2018-12-29 09:05
Check the LD_LIBRARY_PATH environment variable.

**Comment by jcarpent** [comment] 2018-12-29 09:09
@jmirabel is right. It seems that you do not have correctly configured your `LD_LIBRARY_PATH`.

**Comment by ShihaoWang** [comment] 2018-12-29 14:49
Hi @jcarpent,
Sure, the output from this command is 
```
shihao@shihao-OptiPlex-7040:~$ ls -l /usr/local/lib/python2.7/site-packages/pinocchio/
total 7956
-rw-r--r-- 1 root staff    3362 Dec 28 19:06 deprecated.py
-rw-r--r-- 1 root staff    1155 Dec 28 19:06 deprecation.py
-rw-r--r-- 1 root staff    1796 Dec 28 19:06 explog.py
-rw-r--r-- 1 root staff    1001 Dec 28 19:06 __init__.py
-rw-r--r-- 1 root staff 8090630 Dec 28 20:12 libpinocchio_pywrap.so
-rw-r--r-- 1 root staff   15269 Dec 28 19:06 robot_wrapper.py
-rw-r--r-- 1 root staff    2738 Dec 28 19:06 romeo_wrapper.py
-rw-r--r-- 1 root staff    1990 Dec 28 19:06 rpy.py
-rw-r--r-- 1 root staff     149 Dec 28 15:53 shortcuts.py
-rw-r--r-- 1 root staff    4658 Dec 28 19:06 utils.py
``` 
The **libpinocchio.so** is actually installed in 
```
shihao@shihao-OptiPlex-7040:~/pinocchio/build/src$ ls
CMakeFiles  cmake_install.cmake  CTestTestfile.cmake  libpinocchio.so  Makefile
```
I am not sure whether I should copy **libpinocchio.so** to **/usr/local/lib/python2.7/site-packages/pinocchio/**

Hi @jmirabel ,
Yes, I think that my LD_LIBRARY_PATH should be configured correctly. This is the output
```
shihao@shihao-OptiPlex-7040:~$ echo $LD_LIBRARY_PATH
:/opt/openrobots/lib
```
Should I change this LD_LIBRARY_PATH to be sth else?

**Comment by jcarpent** [comment] 2018-12-30 08:19
Yes, you need to compile Pinocchio with URDF support by first installing `urdfdom`.
@ShihaoWang Do you know that Pinocchio can be installed automatically on your computer with all the required dependencies? All the details are reported here: https://stack-of-tasks.github.io/pinocchio/download.html

**Comment by ShihaoWang** [comment] 2018-12-30 20:59
Hi @jcarpent ,
Thanks for telling me about it. I will try to use this robotpkg method to make things easier.

**Comment by jcarpent** [comment] 2019-01-02 09:09
@ShihaoWang Does it work well?

**Comment by ShihaoWang** [comment] 2019-01-02 17:07
@jcarpent Yeah, thanks for checking out with me and I do appreciate the help from you and @jmirabel.

**Comment by jcarpent** [comment] 2019-01-02 17:42
@ShihaoWang Ok. Sounds good to me. I'm going to close this issue then.

**Closed by jcarpent** 2019-01-02 17:42 UTC

**Comment by erwincoumans** [comment] 2019-11-27 21:01
I ran into the same issue when using pip install pinocchio.
Is there any pip command to include buildModelFromUrdf?

**Comment by jcarpent** [comment] 2019-11-27 23:07
Dear @erwincoumans,
I'm not aware of any installation setup for Pinocchio using pip. But for Python bindings, you can use conda:
```
conda install pinocchio -c conda-forge
```
Is it working for you? 
Best,

Justin

PS: for info, we are not currently supporting pip because it is too hard to check and get access to dependencies such as `urdf`, `boost`, etc.

**Comment by hjw-1014** [comment] 2021-05-19 16:53
@jcarpent Hi, sorry, I meet the same issue. 

My OS is **macOS Catalina 10.15.7*.

**I created a conda env (python3.6) and installed Pinocchio using conda**. Then I followed [here](https://gepettoweb.laas.fr/doc/stack-of-tasks/pinocchio/master/doxygen-html/index.html): it reports:

```
Traceback (most recent call last):
  File "/Users/huangjiawei/Google 云端硬盘/1Master_Thesis/pybullet/pinocchio_test2.py", line 14, in <module>
    model    = pinocchio.buildModelFromUrdf(urdf_filename)
AttributeError: module 'pinocchio' has no attribute 'buildModelFromUrdf'

Process finished with exit code 1
```

I also checked the site-packages at `/opt/anaconda3/envs/My_env/bin/python3.6/site-packages/pinocchio`, inside are:
<img width="420" alt="WeChat835ef481e2bbc3aa8886d8a41c1b5e3a" src="https://user-images.githubusercontent.com/59852451/118852519-28612f00-b8d3-11eb-9c92-42eaff0eb881.png">

So here is really not `buildModelFromUrdf`. I think I use conda to install Pinocchio right, even though the installation time is pretty long.

**Comment by jcarpent** [comment] 2021-05-19 17:15
It works perfectly well on my OSX system similar to yours. The issue is on your side.
Please check with a clean conde environment.

**Comment by hjw-1014** [comment] 2021-05-19 17:22
> It works perfectly well on my OSX system similar to yours. The issue is on your side.
> Please check with a clean conde environment.

Hi, I just checked again and built a new env and installed pinocchio, it works now, maybe my conda env problem. Sorry for my mistake and thank you so much for your quick response.

**Comment by alexandre-blanc** [comment] 2022-09-01 09:56
Hi, I seem to be facing a similar issue, maybe also related to #1528.
I run ubuntu 18.04 (bionic) and primarily use python 3.8.

I installed pinocchio from robotpkg following the instructions on the stack-of-tasks website. I selected the py36 version.
I set up the environment variables accordingly. Then, I tried to import the pinocchio package from python 3.6 and python 3.8 interpreters, with the following result :

```
➜  python3  
Python 3.6.9 (default, Jun 29 2022, 11:45:57) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/openrobots/lib/python3.6/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ImportError: libpinocchio.so.2.6.9: cannot open shared object file: No such file or directory
>>> 
➜  python3.8
Python 3.8.13 (default, Apr 19 2022, 00:53:22) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/openrobots/lib/python3.6/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ModuleNotFoundError: No module named 'pinocchio.pinocchio_pywrap'
>>> 
```

I checked the paths and the presence of the pinocchio_pywrap file :
```
➜  echo $PYTHONPATH
/opt/openrobots/lib/python3.6/site-packages:
➜  echo $LD_LIBRARY_PATH 
/opt/openrobots/lib:/opt/openrobots/lib:
➜  ls /opt/openrobots/lib/python3.6/site-packages/pinocchio 
deprecated.py   explog.py    pinocchio_pywrap.cpython-36m-x86_64-linux-gnu.so        __pycache__       romeo_wrapper.py  utils.py
deprecation.py  __init__.py  pinocchio_pywrap.cpython-36m-x86_64-linux-gnu.so.2.6.9  robot_wrapper.py  shortcuts.py      visualize
```

I also tried to look for a `libpinocchio.so.2.6.9` file to no avail :
```
➜  find / -path "/mnt/*" -prune -o -name "*pinocchio*" -print 2>/dev/null
/usr/share/doc/robotpkg-py36-pinocchio
/usr/share/doc/robotpkg-pinocchio
/var/lib/dpkg/info/robotpkg-py36-pinocchio.+SIZE_PKG
/var/lib/dpkg/info/robotpkg-py36-pinocchio.list
/var/lib/dpkg/info/robotpkg-py36-pinocchio.+BUILD_VERSION
/var/lib/dpkg/info/robotpkg-py36-pinocchio.+DESC
/var/lib/dpkg/info/robotpkg-pinocchio.+BUILD_INFO
/var/lib/dpkg/info/robotpkg-py36-pinocchio.md5sums
/var/lib/dpkg/info/robotpkg-pinocchio.+SIZE_PKG
/var/lib/dpkg/info/robotpkg-pinocchio.+SIZE_ALL
/var/lib/dpkg/info/robotpkg-pinocchio.md5sums
/var/lib/dpkg/info/robotpkg-pinocchio.+DESC
/var/lib/dpkg/info/robotpkg-py36-pinocchio.+SIZE_ALL
/var/lib/dpkg/info/robotpkg-py36-pinocchio.+CONTENTS
/var/lib/dpkg/info/robotpkg-pinocchio.list
/var/lib/dpkg/info/robotpkg-pinocchio.+CONTENTS
/var/lib/dpkg/info/robotpkg-py36-pinocchio.+BUILD_INFO
/var/lib/dpkg/info/robotpkg-pinocchio.+BUILD_VERSION
/var/lib/dpkg/info/robotpkg-py36-pinocchio.+COMMENT
/var/lib/dpkg/info/robotpkg-pinocchio.+COMMENT
/opt/openrobots/lib/python3.6/site-packages/pinocchio
/opt/openrobots/lib/python3.6/site-packages/pinocchio/pinocchio_pywrap.cpython-36m-x86_64-linux-gnu.so
/opt/openrobots/lib/python3.6/site-packages/pinocchio/pinocchio_pywrap.cpython-36m-x86_64-linux-gnu.so.2.6.9
/opt/openrobots/share/doc/debian/py36-pinocchio
```
My installation seems fairly clean to me and I don't see any obvious problems. I am not fluent in the build/linking process used to develop python bindings, and I can't figure out what my next step could be. Any help much appreciated.
