### ISSUE TITLE
undefined symbol: _ZN8octomath6Pose6DC1ERKS0_

### ISSUE THREAD

**Issue by GavinYang5** [stack-of-tasks/pinocchio#2438] opened 2024-09-29 02:09 UTC
## Bug description

  File "/usr/local/lib/python3.8/dist-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/__init__.py", line 18, in <module>
    from .pinocchio_pywrap import *
ImportError: /usr/local/lib/python3.8/dist-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/../../../../lib/libhpp-fcl.so: undefined symbol: _ZN8octomath6Pose6DC1ERKS0_

## Reproduction steps

1. Load to '...'

### Docker image

If this is an installation issue, a Docker image to reproduce it

```dockerfile
...
```

### Code

If this is a runtime issue, provide some minimal code to reproduce it:

```
...
```

### System

- OS: [ubuntu 20.04]
- Pinocchio version: [2.7.0]

**Comment by SagarChandra07** [comment] 2024-09-29 02:11
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by GavinYang5** [comment] 2024-09-29 02:18
Sorry, I didn't understand what you meant

**Comment by GavinYang5** [comment] 2024-09-29 03:14
My system is ubuntu20.04

**Comment by jcarpent** [comment] 2024-09-29 21:15
@GavinYang5 If you can, switch to conda.

**Comment by nim65s** [comment] 2024-09-30 09:12
@GavinYang5 : I can't reproduce your issue with a simple
```Dockerfile
FROM ubuntu:20.04

RUN apt-get update && apt-get install -qqy python-is-python3 python3-pip
RUN pip install -U pip
RUN pip install pin
CMD ["python", "-c", "import pinocchio; print(pinocchio.__version__)"]
```

So the issue probably come from your system.

**Comment by jcarpent** [comment] 2024-09-30 09:45
I'm closing the issue thanks to the answer of @nim65s

**Closed** 2024-09-30 09:45 UTC
